name: Blog in Readme

on:
  workflow_dispatch:
  schedule:
    # Once every Sunday
    - cron: 0 0 * * 0

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://blog.athulcyriac.in/index.xml
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          committer_username: GitHub Actions[Bot]
